/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.0 and the DSP System Toolbox 9.2.
 * Generated on: 28-Oct-2019 08:36:14
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 64
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 * Arithmetic        : fixed
 * Numerator         : s8,8 -> [-5.000000e-01 5.000000e-01)
 * Input             : s16,15 -> [-1 1)
 * Filter Internals  : Full Precision
 *   Output          : s25,23 -> [-2 2)  (auto determined)
 *   Product         : s21,23 -> [-1.250000e-01 1.250000e-01)  (auto determined)
 *   Accumulator     : s25,23 -> [-2 2)  (auto determined)
 *   Round Mode      : No rounding
 *   Overflow Mode   : No overflow
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2016a\extern\include\tmwtypes.h 
 */
const int BL = 64;
const int8_T B[64] = {
      1,    1,    1,    0,   0,   -1,   -2,   -2,   -1,   0,    0,   0,
      0,    0,   -1,   -1,    0,    2,    3,   5,   5,    4,    1,   -4,
    -8,  -11,  -11,  -8,   -2,    4,   10,   13,   13,   10,   4,   -2,
    -8,  -11,  -11,  -8,   -4,    1,    4,   5,   5,    3,    2,    0,
     -1,   -1,    0,    0,    0,    0,   0,   -1,   -2,   -2,   -1,   0,
      0,    1,    1,    1
};
